server:
  port: 8080
  servlet:
    context-path: /experience/operationalServices/issuedDeviceAdministration
grpc:
  server:
    port: 9090
    address: 0.0.0.0
    
spring:
  application:
    name: password-management-service
  
logging:
  level:
    root: INFO
    com.ec: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 
               
msd.seg.cli.usuario.api.url: https://${MSD_SEG_CLI_USER_ENDPOINT}/seguridad/v1/cliente/usuario/cambiar-clave
msd.seg.otp.api.url: https://${MSD_SEG_OTP_ENDPOINT}/seguridad/v2/otp/generar 